name: Terraform CI - Pipeline Central

on:
  pull_request:
    branches:
      - main

jobs:

  analisis:
    name: Llamar analisis estatico y seguridad
    uses: ./.github/workflows/tflint-checkov.yaml
    with:
      path: terraform/

  validacion:
    name: Llamar validacion Terraform
    needs: analisis
    uses: ./.github/workflows/validate.yaml
    with:
      path: terraform/

  politicas:
    name: Llamar validacion politicas OPA
    needs: validacion
    uses: ./.github/workflows/opa-validation.yaml
    with:
      path: terraform/
      policies_path: policies/
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}